### ISSUE TITLE
Error: Illegal division by zero at //List.pl line 599, <IN2> chunk 1

### ISSUE THREAD

**Issue by Tony76** [santhilalsubhash/geneSCF#2]
Hi, 

I've just tried to run geneSCF on my own data and got the following error message:
Illegal division by zero at //class/lib/List/Vectorize/lib/List.pl line 599, <IN2> chunk 1
Any suggestion?
Thank you in advance,

Tony

**Comment by santhilalsubhash** [comment]
Please let me know in which operating system are you using.

/santhilal

**Comment by santhilalsubhash** [comment]
JFI: This usually means gene identifier in your input list (genes) and in the input database file (for functional annotation) does not match. But there might be other issues which i never faced before. if possible send your sample input gene list and sample database file. If you are using your own annotation as input please make sure you followed these steps (link below):

https://www.biostars.org/p/150137/#150175

**Comment by Tony76** [comment]
Hi,

Thank you for your reply. I had a look into the biostars link and indeed, it was an annotation issue. The problem is now fixed.

Best regards,

Tony

**Comment by santhilalsubhash** [comment]
All the best. The issue will be closed now.

**Comment by Shahina** [comment]
Hi,

I have already used -m=update option in command and xla folder is generated under db folder too. I also tested the example which is provided in the documentation and it is giving me same error. 

Regards,
S

**Comment by santhilalsubhash** [comment]
can you please enter the command used to run test dataset ?
