### ISSUE TITLE
Unable to start geneSCF

### ISSUE THREAD

**Issue by Tcvalenzuela** [santhilalsubhash/geneSCF#3]
Hi to all
I'm trying to make an analysis of gene ontology in a set of differentially expressed genes of prunus persica. To do so I provide to the program with a list in a .txt file with all the prupes of my analysis and run the following code line 
[CODE]
./geneSCF -m=update -i=GEnes_Go.txt -t=sym -o=/Go_Prupe -db=KEGG -p=yes -org=pper
[/CODE]

and I get the following 

[CODE]
Since you have selected 'update' mode. It will take a while to prepare new updated database
Connecting remote RUD..
processing started....mar ago 30 11:13:14 CLST 2016
Retreiving 129 KEGG pathways for pper
Do not panic. The processing is going on...
Database retreived..You are now ready to use geneSCF with organism pper from --database KEGG
Done....mar ago 30 11:20:23 CLST 2016
=>processing in update started....mar ago 30 11:20:23 CLST 2016
=> Finished retriving database...
=> Calculating statistics...
find: «pper/class/lib/db/yes/kegg_database.txt»: No existe el archivo o el directorio
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
KEGG last updated 
Example input types
---------------
gid |	sym
=> Retreving gene list for yes from KEGG
sh: 1: cannot create pper/mapping/DB/GEnes_Go.txt_gene_list.txt: Directory nonexistent
=> Mapping user list
Can't open perl script "pper/class/scripts/mappingIDS.pl": No existe el archivo o el directorio
sh: 1: cannot create /Go_Prupe/GEnes_Go.txt_user_mapped.list: Directory nonexistent
cat: /Go_Prupe/GEnes_Go.txt_user_mapped.list: No existe el archivo o el directorio
sh: 1: cannot create pper/mapping/GEnes_Go.txt_input_list.txt: Directory nonexistent
wc: pper/mapping/GEnes_Go.txt_input_list.txt: No existe el archivo o el directorio
Note: There were  genes mapped from 324 user provided unique genes (0 %)
Please cross-check your gene identifier.mar ago 30 11:20:25 CLST 2016 finished processing
[/CODE]

And I don't know where to look for the missing files, please help

**Comment by santhilalsubhash** [comment]
Thanks for trying GeneSCF.

## **Problems associated with your commandline:**

1) Missing background genes (All parameters are necessary)

> ./geneSCF -m=update -i=GEnes_Go.txt -t=sym -o=/Go_Prupe -db=KEGG -p=yes -org=pper -**bg=NumberOfBackgroundGenes****

2) The output path you gave is a root path. That is the reason, GeneSCF could not able to create any files. If your directory 'Go_Prupe' and input file is in current path use as below (or use complete path to your directory and input file),

> ./geneSCF -m=update -i=**./GEnes_Go.txt** -t=sym -o=**./Go_Prupe/** -db=KEGG -p=yes -org=pper -bg=#NumberOfBackgroundGenes

Form your error 'cat: /Go_Prupe/GEnes_Go.txt_user_mapped.list' I can see that the problem is associated with your path to out put directory. 

## **Input gene_list format:**

https://www.biostars.org/p/186074/#186110


## **Recommendations:**

1) GeneSCF only works on Linux system, it has been successfully tested on Ubuntu, Mint and Cent OS. Other distributions of Linux might work as well.

2) Use updated version of GeneSCF.

**Comment by Tcvalenzuela** [comment]
I'm still unable to run the analysis, even when I make all the corrections that you recommended
 my code
[CODE]
./geneSCF -m=update -i=./GEnes_Go.txt -t=sym -o=./Go_Prupe -db=KEGG -p=yes -org=pper -bg=26000
[/CODE] 
My output

[CODE]
processing in 'normal' mode started....mar ago 30 16:12:10 CLST 2016
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
KEGG last updated 2016-08-30 16:10
Example input types
---------------
gid |	sym
PRUPE_ppa025708mg	hypothetical
PRUPE_ppa009429mg	hypothetical
PRUPE_ppa018505mg	hypothetical
PRUPE_ppa015092mg	hypothetical
PRUPE_ppa022757mg	hypothetical
PRUPE_ppa023566mg	hypothetical
PRUPE_ppb021368mg	hypothetical
PRUPE_ppa001162mg	hypothetical
PRUPE_ppa024867mg	hypothetical
PRUPE_ppa007569mg	hypothetical
=> Retreving gene list for pper from KEGG
=> Mapping user list
Note: There were 0 genes mapped from 300 user provided unique genes (0 %)
Please cross-check your gene identifier.mar ago 30 16:12:21 CLST 2016 finished processing
[/CODE]

my gen list

PRUPE_ppa010802mg
PRUPE_ppa007083mg
PRUPE_ppa013789mg
PRUPE_ppa001473mg
PRUPE_ppa013101mg
PRUPE_ppa008224mg
PRUPE_ppa002954mg
PRUPE_ppa007364mg
PRUPE_ppa002064mg
PRUPE_ppa000916mg
PRUPE_ppa013714mg
PRUPE_ppa006496mg
PRUPE_ppa003185mg
PRUPE_ppa005486mg
PRUPE_ppa018903mg
PRUPE_ppa007452mg
PRUPE_ppa009745mg
PRUPE_ppa006683mg
PRUPE_ppa000880mg
PRUPE_ppa001379mg
PRUPE_ppa013058mg
PRUPE_ppa009986mg
PRUPE_ppa012967mg
PRUPE_ppa017787mg
PRUPE_ppa000139mg
PRUPE_ppa005434mg
PRUPE_ppa013295mg
PRUPE_ppa011892mg
PRUPE_ppa005153mg
PRUPE_ppa011655mg
PRUPE_ppa016030mg
PRUPE_ppa006561mg
PRUPE_ppa010379mg
PRUPE_ppa011102mg
PRUPE_ppa017695mg
PRUPE_ppa003522mg
PRUPE_ppa002528mg
PRUPE_ppa000729mg
PRUPE_ppa1027229mg
PRUPE_ppa001334mg
PRUPE_ppa008143mg
PRUPE_ppa004276mg
PRUPE_ppa009209mg
PRUPE_ppa008984mg
PRUPE_ppa006694mg
PRUPE_ppa008481mg
PRUPE_ppa011080mg
PRUPE_ppa011425mg
PRUPE_ppa007464mg
PRUPE_ppa007555mg
PRUPE_ppa010195mg
PRUPE_ppa004353mg
PRUPE_ppa013112mg
PRUPE_ppa009772mg
PRUPE_ppa002215mg
PRUPE_ppa022289mg
PRUPE_ppa008288mg
PRUPE_ppa008527mg
PRUPE_ppa002801mg
PRUPE_ppa008190mg
PRUPE_ppa004698mg
PRUPE_ppa002710mg
PRUPE_ppa010728mg
PRUPE_ppa001638mg
PRUPE_ppa000681mg
PRUPE_ppa016913mg
PRUPE_ppa005698mg
PRUPE_ppa018553mg
PRUPE_ppa002291mg
PRUPE_ppa005325mg
PRUPE_ppa021264mg
PRUPE_ppa012197mg
PRUPE_ppa006330mg
PRUPE_ppa005860mg
PRUPE_ppa001826mg
PRUPE_ppa006158mg
PRUPE_ppa011776mg
PRUPE_ppa018863mg
PRUPE_ppa006060mg
PRUPE_ppa009578mg
PRUPE_ppa006240mg
PRUPE_ppa006030mg
PRUPE_ppa006881mg
PRUPE_ppa013189mg
PRUPE_ppa026983mg
PRUPE_ppa001661mg
PRUPE_ppa009023mg
PRUPE_ppa008693mg
PRUPE_ppa009602mg
PRUPE_ppa000135mg
PRUPE_ppa017766mg
PRUPE_ppa014599mg
PRUPE_ppa000167mg
PRUPE_ppa010471mg
PRUPE_ppa003206mg
PRUPE_ppa009705mg
PRUPE_ppa004369mg
PRUPE_ppa003196mg
PRUPE_ppa002897mg
PRUPE_ppa003761mg
PRUPE_ppa001413mg
PRUPE_ppa001744mg
PRUPE_ppa010921mg
PRUPE_ppa011273mg
PRUPE_ppa010684mg
PRUPE_ppa012959mg
PRUPE_ppa010093mg
PRUPE_ppa019585mg
PRUPE_ppa001909mg
PRUPE_ppa007567mg
PRUPE_ppa013521mg
PRUPE_ppa009462mg
PRUPE_ppa009245mg
PRUPE_ppa006675mg
PRUPE_ppa009687mg
PRUPE_ppa000112mg
PRUPE_ppa002354mg
PRUPE_ppa009698mg
PRUPE_ppa006731mg
PRUPE_ppa011192mg
PRUPE_ppa016365mg
PRUPE_ppa002333mg
PRUPE_ppa012441mg
PRUPE_ppa008862mg
PRUPE_ppa006653mg
PRUPE_ppa012362mg
PRUPE_ppa012541mg
PRUPE_ppa006549mg
PRUPE_ppa009324mg
PRUPE_ppa012179mg
PRUPE_ppa010094mg
PRUPE_ppa006139mg
PRUPE_ppa013107mg
PRUPE_ppa010388mg
PRUPE_ppa012057mg
PRUPE_ppa012326mg
PRUPE_ppa006726mg
PRUPE_ppa002999mg
PRUPE_ppa024249mg
PRUPE_ppa003130mg
PRUPE_ppa006458mg
PRUPE_ppa007315mg
PRUPE_ppa018739mg
PRUPE_ppa000974mg
PRUPE_ppa003224mg
PRUPE_ppa011209mg
PRUPE_ppa011556mg
PRUPE_ppa003460mg
PRUPE_ppa008744mg
PRUPE_ppa009464mg
PRUPE_ppa003570mg
PRUPE_ppa003858mg
PRUPE_ppa009588mg
PRUPE_ppa013564mg
PRUPE_ppa001392mg
PRUPE_ppa004942mg
PRUPE_ppa018789mg
PRUPE_ppa009092mg
PRUPE_ppa012720mg
PRUPE_ppa017267mg
PRUPE_ppa022818mg
PRUPE_ppa004776mg
PRUPE_ppa007685mg
PRUPE_ppa008774mg
PRUPE_ppa001777mg
PRUPE_ppa005358mg
PRUPE_ppa010653mg
PRUPE_ppa005765mg
PRUPE_ppa001462mg
PRUPE_ppa024803mg
PRUPE_ppa013097mg
PRUPE_ppa011598mg
PRUPE_ppa013557mg
PRUPE_ppa007935mg
PRUPE_ppa008736mg
PRUPE_ppa010291mg
PRUPE_ppa002234mg
PRUPE_ppa004467mg
PRUPE_ppa009266mg
PRUPE_ppa012426mg
PRUPE_ppa007335mg
PRUPE_ppa008265mg
PRUPE_ppa003090mg
PRUPE_ppa010314mg
PRUPE_ppa003329mg
PRUPE_ppa003265mg
PRUPE_ppa013971mg
PRUPE_ppa003623mg
PRUPE_ppa000651mg
PRUPE_ppa007188mg
PRUPE_ppa002445mg
PRUPE_ppa001814mg
PRUPE_ppa000987mg
PRUPE_ppa012138mg
PRUPE_ppa008613mg
PRUPE_ppa015592mg
PRUPE_ppa009620mg
PRUPE_ppa009112mg
PRUPE_ppa014212mg
PRUPE_ppa015273mg
PRUPE_ppa004740mg
PRUPE_ppa004949mg
PRUPE_ppa008999mg
PRUPE_ppa006443mg
PRUPE_ppa011435mg
PRUPE_ppa006439mg
PRUPE_ppa006797mg
PRUPE_ppa007621mg
PRUPE_ppa004220mg
PRUPE_ppa020283mg
PRUPE_ppa007308mg
PRUPE_ppa021774mg
PRUPE_ppa003432mg
PRUPE_ppa009689mg
PRUPE_ppa012603mg
PRUPE_ppa003000mg
PRUPE_ppa011897mg
PRUPE_ppa011157mg
PRUPE_ppa005607mg
PRUPE_ppa004490mg
PRUPE_ppa010426mg
PRUPE_ppa011002mg
PRUPE_ppa010226mg
PRUPE_ppa003864mg
PRUPE_ppa005092mg
PRUPE_ppa009162mg
PRUPE_ppa002843mg
PRUPE_ppa007071mg
PRUPE_ppa012574mg
PRUPE_ppa012325mg
PRUPE_ppa011229mg
PRUPE_ppa012320mg
PRUPE_ppa011054mg
PRUPE_ppa008075mg
PRUPE_ppa001716mg
PRUPE_ppa026645mg
PRUPE_ppa007574mg
PRUPE_ppa015360mg
PRUPE_ppa002163mg
PRUPE_ppa008420mg
PRUPE_ppa004657mg
PRUPE_ppa016088mg
PRUPE_ppa003676mg
PRUPE_ppa007547mg
PRUPE_ppa011976mg
PRUPE_ppa001187mg
PRUPE_ppa005976mg
PRUPE_ppa007164mg
PRUPE_ppa013244mg
PRUPE_ppa008641mg
PRUPE_ppa007698mg
PRUPE_ppa005254mg
PRUPE_ppa007131mg
PRUPE_ppa013582mg
ppb024948mg
PRUPE_ppa019833mg
PRUPE_ppa007403mg
PRUPE_ppa005330mg
PRUPE_ppa009951mg
PRUPE_ppa012724mg
PRUPE_ppa017381mg
PRUPE_ppa007866mg
PRUPE_ppa002608mg
PRUPE_ppa011179mg
PRUPE_ppa000884mg
PRUPE_ppa009496mg
PRUPE_ppa005671mg
PRUPE_ppa026259mg
ppb023607mg
PRUPE_ppa021647mg
PRUPE_ppa015739mg
PRUPE_ppa009854mg
PRUPE_ppa010511mg
PRUPE_ppa006621mg
PRUPE_ppa007525mg
PRUPE_ppa001754mg
PRUPE_ppa009691mg
PRUPE_ppa002658mg
PRUPE_ppa010275mg
PRUPE_ppa013146mg
PRUPE_ppa020872mg
PRUPE_ppa004156mg
PRUPE_ppa000716mg
PRUPE_ppa009933mg
PRUPE_ppa006673mg
PRUPE_ppa007174mg
PRUPE_ppa005256mg
PRUPE_ppa016712mg
PRUPE_ppa013834mg
PRUPE_ppa013837mg
PRUPE_ppa013865mg
PRUPE_ppa000007mg
PRUPE_ppa013071mg
PRUPE_ppa002913mg
PRUPE_ppa005537mg
PRUPE_ppa000538mg
PRUPE_ppa001772mg
PRUPE_ppa014909mg
PRUPE_ppa007054mg
PRUPE_ppa013777mg

help u.u

**Comment by santhilalsubhash** [comment]
Please also try using the complete path to your input file and also output folder.

Also keep in mind that GeneSCF will not create any output folder. You must give path to existing folder.

**Comment by Tcvalenzuela** [comment]
I do

**Comment by santhilalsubhash** [comment]
Have you done it already using full path?

**Comment by Tcvalenzuela** [comment]
tomas@tomas-HP-Pavilion-15-Notebook-PC[geneSCF-master-source-v1.1-p1] ./geneSCF -m=normal -i=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list -t=sym -o=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ -db=KEGG -p=yes -org=pper -bg=26000 
processing in 'normal' mode started....mar ago 30 18:44:24 CLST 2016
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
KEGG last updated 2016-08-30 16:37
Example input types
---------------
gid |	sym
PRUPE_ppa025708mg	hypothetical
PRUPE_ppa009429mg	hypothetical
PRUPE_ppa018505mg	hypothetical
PRUPE_ppa015092mg	hypothetical
PRUPE_ppa022757mg	hypothetical
PRUPE_ppa023566mg	hypothetical
PRUPE_ppb021368mg	hypothetical
PRUPE_ppa001162mg	hypothetical
PRUPE_ppa024867mg	hypothetical
PRUPE_ppa007569mg	hypothetical
=> Retreving gene list for pper from KEGG
=> Mapping user list
Note: There were 0 genes mapped from 300 user provided unique genes (0 %)
Please cross-check your gene identifier.mar ago 30 18:44:35 CLST 2016 finished processing

**Comment by santhilalsubhash** [comment]
Run this in two step. There might be problem while updating the database.

1)

> ./prepare_database -db=KEGG -org=pper


2)

> ./geneSCF -m=normal -i=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list -t=sym -o=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ -db=KEGG -p=yes -org=pper -bg=26000 

This should solve your issue.

**Comment by Tcvalenzuela** [comment]
I have done that database update more in the morning but I'll try :)

**Comment by Tcvalenzuela** [comment]
Nevertheless I look manually my genes in the file /class/ilb/db/pper/kegg_database.txt and I cuoldent find almost any of my genes. Is that even possible?

**Comment by santhilalsubhash** [comment]
I found the problem use -t=gid instead of 'sym'.

**Comment by Tcvalenzuela** [comment]
I' couldn't*

**Comment by Tcvalenzuela** [comment]
ok and thanks

**Comment by Tcvalenzuela** [comment]
its updating xp

**Comment by santhilalsubhash** [comment]
Please let me know if it is working.

**Comment by Tcvalenzuela** [comment]
tomas@tomas-HP-Pavilion-15-Notebook-PC[geneSCF-master-source-v1.1-p1] ./prepare_database -db=KEGG -org=pper
processing started....mar ago 30 18:50:30 CLST 2016
Retreiving 129 KEGG pathways for pper
Do not panic. The processing is going on...
Database retreived..You are now ready to use geneSCF with organism pper from --database KEGG
Done....mar ago 30 18:57:53 CLST 2016
tomas@tomas-HP-Pavilion-15-Notebook-PC[geneSCF-master-source-v1.1-p1] ./geneSCF -m=normal -i=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list -t=grid -o=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ -db=KEGG -p=yes -org=pper -bg=26000
processing in 'normal' mode started....mar ago 30 18:58:20 CLST 2016
=> Finished retriving database...
=> Calculating statistics...

***
Error opening input file: /home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list
***

Illegal division by zero at /home/tomas/Documentos/geneSCF-master-source-v1.1-p1/class/lib/List/Vectorize/lib/List.pl line 599.
mar ago 30 18:58:20 CLST 2016 finished processing
tomas@tomas-HP-Pavilion-15-Notebook-PC[geneSCF-master-source-v1.1-p1] ./geneSCF -m=normal -i=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list -t=grid -o=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ -db=KEGG -p=yes -org=pper -bg=26000 
processing in 'normal' mode started....mar ago 30 18:58:59 CLST 2016
=> Finished retriving database...
=> Calculating statistics...

***
Error opening input file: /home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list
***

Illegal division by zero at /home/tomas/Documentos/geneSCF-master-source-v1.1-p1/class/lib/List/Vectorize/lib/List.pl line 599.
mar ago 30 18:58:59 CLST 2016 finished processing

**Comment by Tcvalenzuela** [comment]
I think I see this error before in one of yours forum

**Comment by Tcvalenzuela** [comment]
not shown the data set xp

**Comment by santhilalsubhash** [comment]
Did you also try with both 'sym' and 'gid' ?

**Comment by Tcvalenzuela** [comment]
that last one was with grid all the others was with sym

**Comment by santhilalsubhash** [comment]
Which operating system or distribution are you using?

**Comment by Tcvalenzuela** [comment]
Ubuntu

**Comment by Tcvalenzuela** [comment]
I think

**Comment by Tcvalenzuela** [comment]
work

**Comment by Tcvalenzuela** [comment]
tomas@tomas-HP-Pavilion-15-Notebook-PC[geneSCF-master-source-v1.1-p1] ./geneSCF -m=normal -i=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/GEnes_Go.list -t=gid -o=/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ -db=KEGG -p=yes -org=pper -bg=26000
processing in 'normal' mode started....mar ago 30 19:05:57 CLST 2016
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
KEGG last updated 2016-08-30 18:57
Example input types
---------------
gid |	sym
cut: el delimitador debe ser un sólo carácter
Pruebe 'cut --help' para más información.
nohup: se redirige la salida de error a la salida estándar
=================
Run successful. Check your output directory /home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/ 
=================

Parameters used:

Organism:		pper
background genes:	26000
Identitiy:		Entrez GeneID
Database used:		KEGG
Output file:		/home/tomas/Documentos/geneSCF-master-source-v1.1-p1/Go_Prupe/GEnes_Go.list_KEGG_functional_classification.tsv
		WARNING: Your output is not sorted with P-val/FDR.


---------------------

Author: Santhilal Subhash
santhilal.subhash@gu.se
GeneSCF elapse time 4 seconds
mar ago 30 19:06:01 CLST 2016 finished processing

**Comment by santhilalsubhash** [comment]
Is ot working??

**Comment by Tcvalenzuela** [comment]
produce one graph and one .tsv file xp

**Comment by santhilalsubhash** [comment]
Did you get any results in that?

**Comment by Tcvalenzuela** [comment]
but in the tsv file are 53 genes or I'm wrong?

**Comment by Tcvalenzuela** [comment]
https://www.dropbox.com/s/lu4yomt0mtbg8er/GEnes_Go.list_KEGG_pper_functional_classification.tsv?dl=0

**Comment by Tcvalenzuela** [comment]
is this file ok?

**Comment by santhilalsubhash** [comment]
The TSV file usually contains the genes in the first column followed by pathways and statistical values.

**Comment by Tcvalenzuela** [comment]
And (sorry for my non-expertise) but.. what is the right program to view this file? xp

**Comment by santhilalsubhash** [comment]
Yes the file from the above link has the perfect output from GeneSCF. Whever you get this problem in future.

Try to use 'prepare_database' and then run GeneSCF in normal mode. 


Should I close this issue now?? In future if you need any assistance, please report here creating new issue or report on Biostars forum.

**Comment by Tcvalenzuela** [comment]
Yes I'll close this issue, thanks very much for your patience
